export default {
  LIST_CHIP: [1, 5, 10, 25, 100, 500, 1000, 5000],
  API: {
    baseURL: 'https://colla-api.playtime.work/',
    CheckPhone: 'api/auth/check-phone',
    VerifyPhone: 'api/auth/verify-phone',
    CheckAuth: 'api/auth/me',
    UpdateProfile: 'api/auth/profile',
    // GetListProduct: 'api/product',
    Useraddress: 'api/useraddress',
    Order: 'api/order',
    SignInPhone: 'api/auth/signin-by-phone',
    SignUp: 'api/auth/signup',
    SignIn: 'api/auth/signin',
    SendOtp: 'api/auth/send-otp',
    VerifyOtp: 'api/auth/verify-otp',
    Cart: 'api/cart',
    ForgotPassword: 'api/auth/forgot-password',
    ResetPassword: 'api/auth/reset-password',
    Point: 'api/point',
    ImportProduct: 'api/import/product',
    ImportCart: 'api/import/cart',
    ImportOrder: 'api/import/order',

    GetDomain: 'https://api.olbius.com/token',
    // baseURL: 'https://testldmarket.olbius.com/mobileservices/control',
    baseImgURL: 'https://demold.olbius.com',
    urlGetDomain: 'https://api.olbius.com/token',
    Login: '/mobilelogin',
    Logout: '/logout',
    GetCustomer: '/mGetCustomers',
    GetListProduct: '/getPriceTax',
    GetCustomerRegistration: '/mGetCustomerRegistration',
    GetSaleOrder: '/mGetSalesOrders',
    GetOrderDetail: '/mGetSalesOrderDetails',
    GetProductDetail: '/mGetProductInfoDetail',
    GetListPriceChange: '/mGetListPriceChange',
    GetOrderPromotions: '/getOrderPromotions',
    GetDetailPromotion: '/getOrderPromotion',
    GetListPromotionExt: '/mGetListPromotionExt',
    GetPromotionExtInfoDetail: '/mGetPromotionExtInfoDetail',
    GetCustomerReport: '/mGetCustomerReports',
    GetSalesmanReport: '/mGetTurnoverBySalesmanReports',
    CreateCustomerAgent: '/createCustomerAgent',
    ChangePassWord: '/mUpdatePassWordMobilemcs',
    CreateCart: '/createCart',
    ModifyCart: '/modifyCart',
    SubmitOrder: '/submitOrder',
    GetProductStore: '/getProductStore',
    EmptyCart: '/emptycart',
    CreateRegistrationPromotion: '/mcreateRegistrationPromotion',
    SalesmanCheckIn: '/salesmanCheckIn',
    SalesmanCheckOut: '/salesmanCheckOut',
    GetInventoryCusInfo: '/getInventoryCusInfo',
    UpdateInventoryCus: '/updateInventoryCus',
    GetListProductExpRecent: '/mGetListProductExpRecent',
    UpdateQtyProductExpInvent: '/mUpdateQtyProductExpInvent',
    GetAllRoute: '/getAllRoute',
    GetProductByInfoSearch: '/mGetProductByInfoSearch',
    SubmitFbCustomer: '/submitFbCustomer',
    RegisterCustomerAccount: '/mRegisterCustomerAccount',
  },
  RESPONSE_CODES: {
    SUCCESS: {
      SUCCESS: 200,
    },
    ERROR: {
      INTERNAL_SERVER: 500,
      NOT_FOUND: 404,
    },
  },
};
